title: Account
author: fbe3713b-ee52-445b-91d7-de37bd0e8d85
updated_by: fbe3713b-ee52-445b-91d7-de37bd0e8d85
updated_at: 1724672322
blueprint: category_help
img:
  - icon-1-1.svg
content: 'Learn about your account and how to manage it.'
